name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SSH key pair
        id: generate_key
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-actions@your-repo" -f ~/.ssh/id_rsa -N ""
          echo "::set-output name=private_key::$(cat ~/.ssh/id_rsa)"
          echo "::set-output name=public_key::$(cat ~/.ssh/id_rsa.pub)"

      - name: Display Public Key (for debugging, you can remove this later)
        run: cat ~/.ssh/id_rsa.pub

      - name: Copy public key to EC2 instance
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # An existing SSH key to access EC2
        run: |
          echo "${{ steps.generate_key.outputs.public_key }}" | ssh -i <path-to-existing-key> -o StrictHostKeyChecking=no ubuntu@13.60.64.40 "cat >> ~/.ssh/authorized_keys"

      - name: Add generated SSH key to agent
        run: |
          echo "${{ steps.generate_key.outputs.private_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.64.40 << 'EOF'
            cd /var/www/html/your-project
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart apache2
          EOF